# Generated by Django 3.0.2 on 2020-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilefield',
            name='file_field',
            field=models.FileField(upload_to='static/upload_files/'),
        ),
    ]
